### ISSUE TITLE
Error loading vehicle

### ISSUE THREAD

**Issue by juliusmarminge** [Farfar/homeassistant-seatconnect#14]
Today when I set up this integration for my Seat Leon eHybrid it all worked perfectly and I could flip every switch and it would update in the car. Then I left the computer for 30 minutes and when I came back I got the following error in the HA-log:
```console
2022-01-14 11:29:56 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <MY_VIN> for seatconnect
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/seatconnect/__init__.py", line 140, in async_setup_entry
if not await coordinator.async_login():
File "/config/custom_components/seatconnect/__init__.py", line 771, in async_login
await self.connection.get_vehicles()
File "/usr/local/lib/python3.9/site-packages/seatconnect/connection.py", line 660, in get_vehicles
if legacy_vehicles.get('userVehicles', {}).get('vehicle', False):
AttributeError: 'NoneType' object has no attribute 'get'
```
and all the sensors are labeled `unavailable` and switches are greyed out. Any idea of what this might be?

**Comment by Farfar** [comment]
This occurs almost exclusively because of API problems. If you reload integration/restart HA some day(s) later the API should work correctly again.
