### ISSUE TITLE
Stopped working, time format issue

### ISSUE THREAD

**Issue by scoobang** [Farfar/homeassistant-seatconnect#26]
This is what i get since this morning. It was working fine before:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/seatconnect/sensor.py:50
Integration: Seat Connect (documentation, issues)
First occurred: 7:55:32 AM (216 occurrences)
Last logged: 8:19:17 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/seatconnect/sensor.py", line 50, in state
    return self.instrument.state
  File "/usr/local/lib/python3.10/site-packages/seatconnect/dashboard.py", line 124, in state
    val = super().state
  File "/usr/local/lib/python3.10/site-packages/seatconnect/dashboard.py", line 55, in state
    if hasattr(self.vehicle, self.attr):
  File "/usr/local/lib/python3.10/site-packages/seatconnect/vehicle.py", line 1351, in parking_time
    parkTime = datetime.strptime(parkTime_utc,'%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=timezone.utc).astimezone(tz=None)
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Unknown' does not match format '%Y-%m-%dT%H:%M:%SZ'

**Comment by scoobang** [comment]
Sorry false alarm, it was due to a server problem on Seat. 
The App also didn't get updated data.
Works again today, case closed
