### ISSUE TITLE
KeyError preventing initialising integration

### ISSUE THREAD

**Issue by cyriax** [Farfar/homeassistant-seatconnect#56]
Hello, 

(maybe coincidentially) since the update to 2024.5 the integration stopped working throwing a "KeyError".

The setup-process including login and selecting the needed sensors works fine but it failes to load actual data and creating the according entities

2024-05-03 10:48:29.673 WARNING (MainThread) [homeassistant.data_entry_flow] custom_components.seatconnect.config_flow::SeatConnectConfigFlow calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
2024-05-03 10:48:59.858 ERROR (MainThread) [homeassistant.components.switch] Error while setting up seatconnect platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/seatconnect/switch.py", line 25, in async_setup_entry
data = hass.data[DOMAIN][entry.entry_id][DATA]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '4f7aexxxxxxxxxxxxxxxxxxxebde3'
2024-05-03 10:48:59.859 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up seatconnect platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/seatconnect/binary_sensor.py", line 22, in async_setup_entry
data = hass.data[DOMAIN][entry.entry_id][DATA]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '4f7aexxxxxxxxxxxxxxxxxxxebde3'
2024-05-03 10:48:59.859 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up seatconnect platform for device_tracker
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/seatconnect/device_tracker.py", line 18, in async_setup_entry
data = hass.data[DOMAIN][entry.entry_id][DATA]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '4f7aexxxxxxxxxxxxxxxxxxxebde3'
2024-05-03 10:48:59.859 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up seatconnect platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/seatconnect/sensor.py", line 22, in async_setup_entry
data = hass.data[DOMAIN][entry.entry_id][DATA]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '4f7aexxxxxxxxxxxxxxxxxxxebde3'
2024-05-03 10:48:59.860 ERROR (MainThread) [homeassistant.components.lock] Error while setting up seatconnect platform for lock
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/seatconnect/lock.py", line 23, in async_setup_entry
data = hass.data[DOMAIN][entry.entry_id][DATA]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '4f7aexxxxxxxxxxxxxxxxxxxebde3'

**Comment by cyriax** [comment]
Seems to have resolved itself after numerous restarts and uninstall/installs

**Comment by MarcFu** [comment]
On my site, the error is still present.

**Comment by kovu94** [comment]
My Seat-Connect integration has not been working since Friday.
This time there are apparently no new terms and conditions to accept (I tried all links, logged out of all apps and logged in again) and also deleted the integration from HA and reinstalled it.

After the reinstallation, the integration seems to log in, but no more identities are created, I see the following error message in the log:

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:364
Integration: Switch (documentation, problems)
Occurred for the first time: 20. July 2024 at 15:01:37 (9 occurrences)
Last logged: 07:44:58

Error while setting up seatconnect platform for switch
Traceback (most recent call last):
  File “/usr/src/homeassistant/homeassistant/helpers/entity_platform.py”, line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File “/config/custom_components/seatconnect/switch.py”, line 25, in async_setup_entry
    data = hass.data[DOMAIN][entry.entry_id][DATA]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'd5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxa9b6'

Otherwise there were no changes on my part.

My HA:
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0
Installed on Intel NUC x86-64

---

Edit:
Re-Downloaded SeatConnect via HACS and did a restart of HA. After that all entities are back online.
Strange behaviour...

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
