### ISSUE TITLE
Errors writing parameters to Seat vehicle

### ISSUE THREAD

**Issue by tulkarxxx** [Farfar/homeassistant-seatconnect#8]
Hi,  app is reading perfectly all values, I have an electric car and I want to modify charging timers using some logic, but even manually when I try to change a parameter I get an error, picture attached.

![error](https://user-images.githubusercontent.com/66320480/136237278-a9d2d185-cf5d-499d-a8af-8b744c2b7511.jpg)

**Comment by tofferlicious** [comment]
Hi, I get the same error.
This is the error log if someone is interested:

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/seatconnect/switch.py", line 57, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.9/site-packages/seatconnect/dashboard.py", line 698, in turn_on
    await self.vehicle.set_timer_active(id=1, action="on")
  File "/usr/local/lib/python3.9/site-packages/seatconnect/vehicle.py", line 398, in set_timer_active
    return await self._set_timers(data)
  File "/usr/local/lib/python3.9/site-packages/seatconnect/vehicle.py", line 529, in _set_timers
    raise SeatException('Failed to set departure timer schedule')
seatconnect.exceptions.SeatException: Failed to set departure timer schedule

**Comment by Farfar** [comment]
This is most probably due to invalid request format. Either way I won't be able to fix this since I don't have a Seat myself to test on.

**Comment by Farfar** [comment]
> 

I need more complete log than this to troubleshoot. Please include a few rows prior as well. There should at least be one warning row before the traceback.

**Comment by tofferlicious** [comment]
> > 
> 
> I need more complete log than this to troubleshoot. Please include a few rows prior as well. There should at least be one warning row before the traceback.

Logger: seatconnect.vehicle
Source: /usr/local/lib/python3.9/site-packages/seatconnect/vehicle.py:527
First occurred: 14:42:56 (1 occurrences)
Last logged: 14:42:56

Failed to execute departure timer request - getDeparturetimer() missing 1 required positional argument: 'baseurl'

**Comment by Farfar** [comment]
> 

Please test latest updated release and report back. I checked the code and this error should not appear, not in latest code at least.

**Comment by tofferlicious** [comment]
You are right, now it works!
Thanks 👍

**Comment by Farfar** [comment]
Great! Closing issue.
